# Theme: https://github.com/niklasbuschmann/contrast

title: "_scurity"
author: "ismisepaul"
description: "These are mainly my notes, which can be anything from product security, software supply chain, software development, tech, conference notes."
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header
dark_header: true           # keep the header dark

paginate: 5

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "README.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - { title: Mail, icon: envelope, url: "mailto:ismisepaul@proton.me" }
  - { title: Bluesky, icon: bluesky, url: "https://bsky.app/profile/ismisepaul.bsky.social" }
  - { title: Github, icon: github, url: "https://github.com/ismisepaul" }
  - { title: Keybase, icon: keybase, url: "https://keybase.io/ismisepaul" }
  - { title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 - jekyll-paginate
